name: Run Social Bot Every 15 Min
on:
  push:
    branches: [ main ]
  schedule:
    # هذا السطر يخبر GitHub بتشغيل البوت كل 15 دقيقة
    - cron: '*/15 * * * *'

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # هذه الميزة تسرع العمل بتبديل الملفات المحملة سابقاً (Caching)
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install chromium

      - name: Execute Bot
        run: node index.js

